// Country code to name mapping
export const countryNames: Record<string, string> = {
  "AF": "Afghanistan", "AL": "Albania", "DZ": "Algeria", "AS": "American Samoa", "AD": "Andorra",
  "AO": "Angola", "AI": "Anguilla", "AQ": "Antarctica", "AG": "Antigua and Barbuda", "AR": "Argentina",
  "AM": "Armenia", "AW": "Aruba", "AU": "Australia", "AT": "Austria", "AZ": "Azerbaijan",
  "BS": "Bahamas", "BH": "Bahrain", "BD": "Bangladesh", "BB": "Barbados", "BY": "Belarus",
  "BE": "Belgium", "BZ": "Belize", "BJ": "Benin", "BM": "Bermuda", "BT": "Bhutan",
  "BO": "Bolivia", "BA": "Bosnia and Herzegovina", "BW": "Botswana", "BR": "Brazil", "IO": "British Indian Ocean Territory",
  "BN": "Brunei", "BG": "Bulgaria", "BF": "Burkina Faso", "BI": "Burundi", "KH": "Cambodia",
  "CM": "Cameroon", "CA": "Canada", "CV": "Cape Verde", "KY": "Cayman Islands", "CF": "Central African Republic",
  "TD": "Chad", "CL": "Chile", "CN": "China", "CX": "Christmas Island", "CC": "Cocos Islands",
  "CO": "Colombia", "KM": "Comoros", "CG": "Congo", "CD": "Congo Democratic Republic", "CK": "Cook Islands",
  "CR": "Costa Rica", "HR": "Croatia", "CU": "Cuba", "CY": "Cyprus", "CZ": "Czech Republic",
  "DK": "Denmark", "DJ": "Djibouti", "DM": "Dominica", "DO": "Dominican Republic", "EC": "Ecuador",
  "EG": "Egypt", "SV": "El Salvador", "GQ": "Equatorial Guinea", "ER": "Eritrea", "EE": "Estonia",
  "ET": "Ethiopia", "FK": "Falkland Islands", "FO": "Faroe Islands", "FJ": "Fiji", "FI": "Finland",
  "FR": "France", "GF": "French Guiana", "PF": "French Polynesia", "GA": "Gabon", "GM": "Gambia",
  "GE": "Georgia", "DE": "Germany", "GH": "Ghana", "GI": "Gibraltar", "GR": "Greece",
  "GL": "Greenland", "GD": "Grenada", "GP": "Guadeloupe", "GU": "Guam", "GT": "Guatemala",
  "GG": "Guernsey", "GN": "Guinea", "GW": "Guinea-Bissau", "GY": "Guyana", "HT": "Haiti",
  "VA": "Vatican City", "HN": "Honduras", "HK": "Hong Kong", "HU": "Hungary", "IS": "Iceland",
  "IN": "India", "ID": "Indonesia", "IR": "Iran", "IQ": "Iraq", "IE": "Ireland",
  "IM": "Isle of Man", "IL": "Israel", "IT": "Italy", "JM": "Jamaica", "JP": "Japan",
  "JE": "Jersey", "JO": "Jordan", "KZ": "Kazakhstan", "KE": "Kenya", "KI": "Kiribati",
  "KP": "North Korea", "KR": "South Korea", "KW": "Kuwait", "KG": "Kyrgyzstan", "LA": "Laos",
  "LV": "Latvia", "LB": "Lebanon", "LS": "Lesotho", "LR": "Liberia", "LY": "Libya",
  "LI": "Liechtenstein", "LT": "Lithuania", "LU": "Luxembourg", "MO": "Macao", "MK": "North Macedonia",
  "MG": "Madagascar", "MW": "Malawi", "MY": "Malaysia", "MV": "Maldives", "ML": "Mali",
  "MT": "Malta", "MH": "Marshall Islands", "MQ": "Martinique", "MR": "Mauritania", "MU": "Mauritius",
  "YT": "Mayotte", "MX": "Mexico", "FM": "Micronesia", "MD": "Moldova", "MC": "Monaco",
  "MN": "Mongolia", "ME": "Montenegro", "MS": "Montserrat", "MA": "Morocco", "MZ": "Mozambique",
  "MM": "Myanmar", "NA": "Namibia", "NR": "Nauru", "NP": "Nepal", "NL": "Netherlands",
  "NC": "New Caledonia", "NZ": "New Zealand", "NI": "Nicaragua", "NE": "Niger", "NG": "Nigeria",
  "NU": "Niue", "NF": "Norfolk Island", "MP": "Northern Mariana Islands", "NO": "Norway", "OM": "Oman",
  "PK": "Pakistan", "PW": "Palau", "PS": "Palestine", "PA": "Panama", "PG": "Papua New Guinea",
  "PY": "Paraguay", "PE": "Peru", "PH": "Philippines", "PN": "Pitcairn", "PL": "Poland",
  "PT": "Portugal", "PR": "Puerto Rico", "QA": "Qatar", "RO": "Romania", "RU": "Russia",
  "RW": "Rwanda", "RE": "Réunion", "BL": "Saint Barthélemy", "SH": "Saint Helena", "KN": "Saint Kitts and Nevis",
  "LC": "Saint Lucia", "MF": "Saint Martin", "PM": "Saint Pierre and Miquelon", "VC": "Saint Vincent and the Grenadines", "WS": "Samoa",
  "SM": "San Marino", "ST": "São Tomé and Príncipe", "SA": "Saudi Arabia", "SN": "Senegal", "RS": "Serbia",
  "SC": "Seychelles", "SL": "Sierra Leone", "SG": "Singapore", "SK": "Slovakia", "SI": "Slovenia",
  "SB": "Solomon Islands", "SO": "Somalia", "ZA": "South Africa", "SS": "South Sudan", "GS": "South Georgia and the South Sandwich Islands",
  "ES": "Spain", "LK": "Sri Lanka", "SD": "Sudan", "SR": "Suriname", "SJ": "Svalbard and Jan Mayen",
  "SZ": "Eswatini", "SE": "Sweden", "CH": "Switzerland", "SY": "Syria", "TW": "Taiwan",
  "TJ": "Tajikistan", "TZ": "Tanzania", "TH": "Thailand", "TL": "Timor-Leste", "TG": "Togo",
  "TK": "Tokelau", "TO": "Tonga", "TT": "Trinidad and Tobago", "TN": "Tunisia", "TR": "Turkey",
  "TM": "Turkmenistan", "TC": "Turks and Caicos Islands", "TV": "Tuvalu", "UG": "Uganda", "UA": "Ukraine",
  "AE": "United Arab Emirates", "GB": "United Kingdom", "US": "United States", "UY": "Uruguay", "UZ": "Uzbekistan",
  "VU": "Vanuatu", "VE": "Venezuela", "VN": "Vietnam", "VG": "British Virgin Islands", "VI": "US Virgin Islands",
  "WF": "Wallis and Futuna", "YE": "Yemen", "ZM": "Zambia", "ZW": "Zimbabwe"
};

// Countries sorted by dial code for better UX
export const countries = [
  { code: "US", dial_code: "+1", flag: "🇺🇸" },
  { code: "CA", dial_code: "+1", flag: "🇨🇦" },
  { code: "KZ", dial_code: "+7", flag: "🇰🇿" },
  { code: "RU", dial_code: "+7", flag: "🇷🇺" },
  { code: "EG", dial_code: "+20", flag: "🇪🇬" },
  { code: "ZA", dial_code: "+27", flag: "🇿🇦" },
  { code: "GR", dial_code: "+30", flag: "🇬🇷" },
  { code: "NL", dial_code: "+31", flag: "🇳🇱" },
  { code: "BE", dial_code: "+32", flag: "🇧🇪" },
  { code: "FR", dial_code: "+33", flag: "🇫🇷" },
  { code: "ES", dial_code: "+34", flag: "🇪🇸" },
  { code: "HU", dial_code: "+36", flag: "🇭🇺" },
  { code: "IT", dial_code: "+39", flag: "🇮🇹" },
  { code: "RO", dial_code: "+40", flag: "🇷🇴" },
  { code: "CH", dial_code: "+41", flag: "🇨🇭" },
  { code: "AT", dial_code: "+43", flag: "🇦🇹" },
  { code: "GB", dial_code: "+44", flag: "🇬🇧" },
  { code: "GG", dial_code: "+44", flag: "🇬🇬" },
  { code: "IM", dial_code: "+44", flag: "🇮🇲" },
  { code: "JE", dial_code: "+44", flag: "🇯🇪" },
  { code: "DK", dial_code: "+45", flag: "🇩🇰" },
  { code: "SE", dial_code: "+46", flag: "🇸🇪" },
  { code: "NO", dial_code: "+47", flag: "🇳🇴" },
  { code: "SJ", dial_code: "+47", flag: "🇸🇯" },
  { code: "PL", dial_code: "+48", flag: "🇵🇱" },
  { code: "DE", dial_code: "+49", flag: "🇩🇪" },
  { code: "PE", dial_code: "+51", flag: "🇵🇪" },
  { code: "MX", dial_code: "+52", flag: "🇲🇽" },
  { code: "CU", dial_code: "+53", flag: "🇨🇺" },
  { code: "AR", dial_code: "+54", flag: "🇦🇷" },
  { code: "BR", dial_code: "+55", flag: "🇧🇷" },
  { code: "CL", dial_code: "+56", flag: "🇨🇱" },
  { code: "CO", dial_code: "+57", flag: "🇨🇴" },
  { code: "VE", dial_code: "+58", flag: "🇻🇪" },
  { code: "MY", dial_code: "+60", flag: "🇲🇾" },
  { code: "AU", dial_code: "+61", flag: "🇦🇺" },
  { code: "CX", dial_code: "+61", flag: "🇨🇽" },
  { code: "CC", dial_code: "+61", flag: "🇨🇨" },
  { code: "ID", dial_code: "+62", flag: "🇮🇩" },
  { code: "PH", dial_code: "+63", flag: "🇵🇭" },
  { code: "NZ", dial_code: "+64", flag: "🇳🇿" },
  { code: "PN", dial_code: "+64", flag: "🇵🇳" },
  { code: "SG", dial_code: "+65", flag: "🇸🇬" },
  { code: "TH", dial_code: "+66", flag: "🇹🇭" },
  { code: "JP", dial_code: "+81", flag: "🇯🇵" },
  { code: "KR", dial_code: "+82", flag: "🇰🇷" },
  { code: "VN", dial_code: "+84", flag: "🇻🇳" },
  { code: "CN", dial_code: "+86", flag: "🇨🇳" },
  { code: "TR", dial_code: "+90", flag: "🇹🇷" },
  { code: "IN", dial_code: "+91", flag: "🇮🇳" },
  { code: "PK", dial_code: "+92", flag: "🇵🇰" },
  { code: "AF", dial_code: "+93", flag: "🇦🇫" },
  { code: "LK", dial_code: "+94", flag: "🇱🇰" },
  { code: "MM", dial_code: "+95", flag: "🇲🇲" },
  { code: "IR", dial_code: "+98", flag: "🇮🇷" },
  { code: "SS", dial_code: "+211", flag: "🇸🇸" },
  { code: "MA", dial_code: "+212", flag: "🇲🇦" },
  { code: "DZ", dial_code: "+213", flag: "🇩🇿" },
  { code: "TN", dial_code: "+216", flag: "🇹🇳" },
  { code: "LY", dial_code: "+218", flag: "🇱🇾" },
  { code: "GM", dial_code: "+220", flag: "🇬🇲" },
  { code: "SN", dial_code: "+221", flag: "🇸🇳" },
  { code: "MR", dial_code: "+222", flag: "🇲🇷" },
  { code: "ML", dial_code: "+223", flag: "🇲🇱" },
  { code: "GN", dial_code: "+224", flag: "🇬🇳" },
  { code: "CI", dial_code: "+225", flag: "🇨🇮" },
  { code: "BF", dial_code: "+226", flag: "🇧🇫" },
  { code: "NE", dial_code: "+227", flag: "🇳🇪" },
  { code: "TG", dial_code: "+228", flag: "🇹🇬" },
  { code: "BJ", dial_code: "+229", flag: "🇧🇯" },
  { code: "MU", dial_code: "+230", flag: "🇲🇺" },
  { code: "LR", dial_code: "+231", flag: "🇱🇷" },
  { code: "SL", dial_code: "+232", flag: "🇸🇱" },
  { code: "GH", dial_code: "+233", flag: "🇬🇭" },
  { code: "NG", dial_code: "+234", flag: "🇳🇬" },
  { code: "TD", dial_code: "+235", flag: "🇹🇩" },
  { code: "CF", dial_code: "+236", flag: "🇨🇫" },
  { code: "CM", dial_code: "+237", flag: "🇨🇲" },
  { code: "CV", dial_code: "+238", flag: "🇨🇻" },
  { code: "ST", dial_code: "+239", flag: "🇸🇹" },
  { code: "GQ", dial_code: "+240", flag: "🇬🇶" },
  { code: "GA", dial_code: "+241", flag: "🇬🇦" },
  { code: "CG", dial_code: "+242", flag: "🇨🇬" },
  { code: "CD", dial_code: "+243", flag: "🇨🇩" },
  { code: "AO", dial_code: "+244", flag: "🇦🇴" },
  { code: "GW", dial_code: "+245", flag: "🇬🇼" },
  { code: "IO", dial_code: "+246", flag: "🇮🇴" },
  { code: "SC", dial_code: "+248", flag: "🇸🇨" },
  { code: "SD", dial_code: "+249", flag: "🇸🇩" },
  { code: "RW", dial_code: "+250", flag: "🇷🇼" },
  { code: "ET", dial_code: "+251", flag: "🇪🇹" },
  { code: "SO", dial_code: "+252", flag: "🇸🇴" },
  { code: "DJ", dial_code: "+253", flag: "🇩🇯" },
  { code: "KE", dial_code: "+254", flag: "🇰🇪" },
  { code: "TZ", dial_code: "+255", flag: "🇹🇿" },
  { code: "UG", dial_code: "+256", flag: "🇺🇬" },
  { code: "BI", dial_code: "+257", flag: "🇧🇮" },
  { code: "MZ", dial_code: "+258", flag: "🇲🇿" },
  { code: "ZM", dial_code: "+260", flag: "🇿🇲" },
  { code: "MG", dial_code: "+261", flag: "🇲🇬" },
  { code: "RE", dial_code: "+262", flag: "🇷🇪" },
  { code: "YT", dial_code: "+262", flag: "🇾🇹" },
  { code: "ZW", dial_code: "+263", flag: "🇿🇼" },
  { code: "NA", dial_code: "+264", flag: "🇳🇦" },
  { code: "MW", dial_code: "+265", flag: "🇲🇼" },
  { code: "LS", dial_code: "+266", flag: "🇱🇸" },
  { code: "BW", dial_code: "+267", flag: "🇧🇼" },
  { code: "SZ", dial_code: "+268", flag: "🇸🇿" },
  { code: "KM", dial_code: "+269", flag: "🇰🇲" },
  { code: "SH", dial_code: "+290", flag: "🇸🇭" },
  { code: "ER", dial_code: "+291", flag: "🇪🇷" },
  { code: "AW", dial_code: "+297", flag: "🇦🇼" },
  { code: "FO", dial_code: "+298", flag: "🇫🇴" },
  { code: "GL", dial_code: "+299", flag: "🇬🇱" },
  { code: "GI", dial_code: "+350", flag: "🇬🇮" },
  { code: "PT", dial_code: "+351", flag: "🇵🇹" },
  { code: "LU", dial_code: "+352", flag: "🇱🇺" },
  { code: "IE", dial_code: "+353", flag: "🇮🇪" },
  { code: "IS", dial_code: "+354", flag: "🇮🇸" },
  { code: "AL", dial_code: "+355", flag: "🇦🇱" },
  { code: "MT", dial_code: "+356", flag: "🇲🇹" },
  { code: "CY", dial_code: "+357", flag: "🇨🇾" },
  { code: "FI", dial_code: "+358", flag: "🇫🇮" },
  { code: "BG", dial_code: "+359", flag: "🇧🇬" },
  { code: "LT", dial_code: "+370", flag: "🇱🇹" },
  { code: "LV", dial_code: "+371", flag: "🇱🇻" },
  { code: "EE", dial_code: "+372", flag: "🇪🇪" },
  { code: "MD", dial_code: "+373", flag: "🇲🇩" },
  { code: "AM", dial_code: "+374", flag: "🇦🇲" },
  { code: "BY", dial_code: "+375", flag: "🇧🇾" },
  { code: "AD", dial_code: "+376", flag: "🇦🇩" },
  { code: "MC", dial_code: "+377", flag: "🇲🇨" },
  { code: "SM", dial_code: "+378", flag: "🇸🇲" },
  { code: "VA", dial_code: "+379", flag: "🇻🇦" },
  { code: "UA", dial_code: "+380", flag: "🇺🇦" },
  { code: "RS", dial_code: "+381", flag: "🇷🇸" },
  { code: "ME", dial_code: "+382", flag: "🇲🇪" },
  { code: "HR", dial_code: "+385", flag: "🇭🇷" },
  { code: "SI", dial_code: "+386", flag: "🇸🇮" },
  { code: "BA", dial_code: "+387", flag: "🇧🇦" },
  { code: "MK", dial_code: "+389", flag: "🇲🇰" },
  { code: "CZ", dial_code: "+420", flag: "🇨🇿" },
  { code: "SK", dial_code: "+421", flag: "🇸🇰" },
  { code: "LI", dial_code: "+423", flag: "🇱🇮" },
  { code: "FK", dial_code: "+500", flag: "🇫🇰" },
  { code: "GS", dial_code: "+500", flag: "🇬🇸" },
  { code: "BZ", dial_code: "+501", flag: "🇧🇿" },
  { code: "GT", dial_code: "+502", flag: "🇬🇹" },
  { code: "SV", dial_code: "+503", flag: "🇸🇻" },
  { code: "HN", dial_code: "+504", flag: "🇭🇳" },
  { code: "NI", dial_code: "+505", flag: "🇳🇮" },
  { code: "CR", dial_code: "+506", flag: "🇨🇷" },
  { code: "PA", dial_code: "+507", flag: "🇵🇦" },
  { code: "PM", dial_code: "+508", flag: "🇵🇲" },
  { code: "HT", dial_code: "+509", flag: "🇭🇹" },
  { code: "GP", dial_code: "+590", flag: "🇬🇵" },
  { code: "BL", dial_code: "+590", flag: "🇧🇱" },
  { code: "MF", dial_code: "+590", flag: "🇲🇫" },
  { code: "BO", dial_code: "+591", flag: "🇧🇴" },
  { code: "GY", dial_code: "+592", flag: "🇬🇾" },
  { code: "EC", dial_code: "+593", flag: "🇪🇨" },
  { code: "GF", dial_code: "+594", flag: "🇬🇫" },
  { code: "PY", dial_code: "+595", flag: "🇵🇾" },
  { code: "MQ", dial_code: "+596", flag: "🇲🇶" },
  { code: "SR", dial_code: "+597", flag: "🇸🇷" },
  { code: "UY", dial_code: "+598", flag: "🇺🇾" },
  { code: "BQ", dial_code: "+599", flag: "🇧🇶" },
  { code: "TL", dial_code: "+670", flag: "🇹🇱" },
  { code: "NF", dial_code: "+672", flag: "🇳🇫" },
  { code: "AQ", dial_code: "+672", flag: "🇦🇶" },
  { code: "BN", dial_code: "+673", flag: "🇧🇳" },
  { code: "NR", dial_code: "+674", flag: "🇳🇷" },
  { code: "PG", dial_code: "+675", flag: "🇵🇬" },
  { code: "TO", dial_code: "+676", flag: "🇹🇴" },
  { code: "SB", dial_code: "+677", flag: "🇸🇧" },
  { code: "VU", dial_code: "+678", flag: "🇻🇺" },
  { code: "FJ", dial_code: "+679", flag: "🇫🇯" },
  { code: "PW", dial_code: "+680", flag: "🇵🇼" },
  { code: "WF", dial_code: "+681", flag: "🇼🇫" },
  { code: "CK", dial_code: "+682", flag: "🇨🇰" },
  { code: "NU", dial_code: "+683", flag: "🇳🇺" },
  { code: "WS", dial_code: "+685", flag: "🇼🇸" },
  { code: "KI", dial_code: "+686", flag: "🇰🇮" },
  { code: "NC", dial_code: "+687", flag: "🇳🇨" },
  { code: "TV", dial_code: "+688", flag: "🇹🇻" },
  { code: "PF", dial_code: "+689", flag: "🇵🇫" },
  { code: "TK", dial_code: "+690", flag: "🇹🇰" },
  { code: "FM", dial_code: "+691", flag: "🇫🇲" },
  { code: "MH", dial_code: "+692", flag: "🇲🇭" },
  { code: "KP", dial_code: "+850", flag: "🇰🇵" },
  { code: "HK", dial_code: "+852", flag: "🇭🇰" },
  { code: "MO", dial_code: "+853", flag: "🇲🇴" },
  { code: "KH", dial_code: "+855", flag: "🇰🇭" },
  { code: "LA", dial_code: "+856", flag: "🇱🇦" },
  { code: "BD", dial_code: "+880", flag: "🇧🇩" },
  { code: "TW", dial_code: "+886", flag: "🇹🇼" },
  { code: "MV", dial_code: "+960", flag: "🇲🇻" },
  { code: "LB", dial_code: "+961", flag: "🇱🇧" },
  { code: "JO", dial_code: "+962", flag: "🇯🇴" },
  { code: "SY", dial_code: "+963", flag: "🇸🇾" },
  { code: "IQ", dial_code: "+964", flag: "🇮🇶" },
  { code: "KW", dial_code: "+965", flag: "🇰🇼" },
  { code: "SA", dial_code: "+966", flag: "🇸🇦" },
  { code: "YE", dial_code: "+967", flag: "🇾🇪" },
  { code: "OM", dial_code: "+968", flag: "🇴🇲" },
  { code: "PS", dial_code: "+970", flag: "🇵🇸" },
  { code: "AE", dial_code: "+971", flag: "🇦🇪" },
  { code: "IL", dial_code: "+972", flag: "🇮🇱" },
  { code: "BH", dial_code: "+973", flag: "🇧🇭" },
  { code: "QA", dial_code: "+974", flag: "🇶🇦" },
  { code: "BT", dial_code: "+975", flag: "🇧🇹" },
  { code: "MN", dial_code: "+976", flag: "🇲🇳" },
  { code: "NP", dial_code: "+977", flag: "🇳🇵" },
  { code: "TJ", dial_code: "+992", flag: "🇹🇯" },
  { code: "TM", dial_code: "+993", flag: "🇹🇲" },
  { code: "AZ", dial_code: "+994", flag: "🇦🇿" },
  { code: "GE", dial_code: "+995", flag: "🇬🇪" },
  { code: "KG", dial_code: "+996", flag: "🇰🇬" },
  { code: "UZ", dial_code: "+998", flag: "🇺🇿" },
  { code: "AS", dial_code: "+1684", flag: "🇦🇸" },
  { code: "AI", dial_code: "+1264", flag: "🇦🇮" },
  { code: "AG", dial_code: "+1268", flag: "🇦🇬" },
  { code: "BS", dial_code: "+1242", flag: "🇧🇸" },
  { code: "BB", dial_code: "+1246", flag: "🇧🇧" },
  { code: "BM", dial_code: "+1441", flag: "🇧🇲" },
  { code: "VG", dial_code: "+1284", flag: "🇻🇬" },
  { code: "KY", dial_code: "+1345", flag: "🇰🇾" },
  { code: "DM", dial_code: "+1767", flag: "🇩🇲" },
  { code: "DO", dial_code: "+1849", flag: "🇩🇴" },
  { code: "GD", dial_code: "+1473", flag: "🇬🇩" },
  { code: "GU", dial_code: "+1671", flag: "🇬🇺" },
  { code: "JM", dial_code: "+1876", flag: "🇯🇲" },
  { code: "MS", dial_code: "+1664", flag: "🇲🇸" },
  { code: "MP", dial_code: "+1670", flag: "🇲🇵" },
  { code: "PR", dial_code: "+1939", flag: "🇵🇷" },
  { code: "KN", dial_code: "+1869", flag: "🇰🇳" },
  { code: "LC", dial_code: "+1758", flag: "🇱🇨" },
  { code: "VC", dial_code: "+1784", flag: "🇻🇨" },
  { code: "TT", dial_code: "+1868", flag: "🇹🇹" },
  { code: "TC", dial_code: "+1649", flag: "🇹🇨" },
  { code: "VI", dial_code: "+1340", flag: "🇻🇮" }
];