// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skocnzoyobnoyyegfzdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrb2Nuem95b2Jub3l5ZWdmemR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxNDIxODksImV4cCI6MjA1MjcxODE4OX0.Ql_yqfY3VoILYMG1iYHiNxD-aOM4dSLIMiPAN4CFQog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);